version: '3'

services:
  dollar_exchange_rate_argentine_banks:
    container_name: dollar_exchange_rate_argentine_banks
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
    restart: always
